Team4 question12
Allegheny-Computer-Science-203-S2020/cs203-S2020-management pull request #13
Opened 2020-01-27 19:02 UTC by Cory-Wiard

We answered the question about when a team will know they are finished with implementation of software project. We focused on three groups that were compiling and running the program, meeting all checks, and following the assessment and conduct guides.

2020-01-27 20:12 UTC, schultzh commented
There are currently merge conflict in this PR. I would suggest merging master into your branch to get those updates.

2020-01-28 17:17 UTC, corlettim commented on management.md
> +  know they have finished the implementation of the project by running through
"is by running through" not just "by running through"

2020-01-28 17:26 UTC, schultzh requested changes

2020-01-28 17:26 UTC, schultzh commented on management.md
> +  project because of three reasons. First, our software project will not only
"because of three reasons" phrasing is very basic - maybe say something like: "when the following is complete"

2020-01-28 19:43 UTC, corlettim commented on management.md
> +  given at the beginning of the project. The final thing the team should do to
"task" instead of thing

2020-01-28 19:45 UTC, corlettim approved these changes

2020-01-28 19:47 UTC, enpuyou approved these changes

2020-01-28 19:49 UTC, noorbuchi approved these changes

2020-01-28 19:50 UTC, schultzh approved these changes
Looks good!

2020-01-28 19:51 UTC, lussierc approved these changes
The additions in this PR provided valuable insights to answer the question.

2020-01-28 19:54 UTC, merged